### ISSUE TITLE
We need better milk representation in the fridge!

### ISSUE THREAD

**Issue by DaazKu** [vanilla/milk#2]
![](https://www.lafamilledulait.com/static/public/img/products/chocolat/glass.png)

**Comment by linc** [comment]
I'm becoming concerned about scope creep. Does this require brown cows? Or can we use a third-party milk distribution container?

**Comment by rhysboswarva** [comment]
Buy it in bags. Then you can stock up and freeze it.

![image](https://user-images.githubusercontent.com/923781/57103764-a3f3e180-6cf4-11e9-94f3-f837b099f890.png)

(comes in chocolate too)

**Comment by slafleche** [comment]
What about milk shakes? How do we plan on shaking the cows?

**Comment by DaazKu** [comment]
EZ https://www.youtube.com/watch?v=1IPBkUtziMg

**Comment by slafleche** [comment]
> EZ [youtube.com/watch?v=1IPBkUtziMg](https://www.youtube.com/watch?v=1IPBkUtziMg)

Easy? That looks like a LOT of work for a milk shake...
